package lufthansa

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"

	"github.com/tmaxmax/lufthansaapi/types"
)

// processLimitOffset transforms the general limit and offset parameters,
// which are available for most of the API requests, into an usable string
// for creating the API request URL.
func processLimitOffset(l, o int) string {
	var ret string
	if l != 0 {
		ret += fmt.Sprintf("limit=%d", l)
	}
	if o != 0 {
		if strings.Contains(ret, "limit") {
			ret += fmt.Sprintf("&offset=%d", o)
		} else {
			ret += fmt.Sprintf("offset=%d", o)
		}
	}
	return ret
}

// decodeErrors unmarshals the JSON response according to the HTTP response error
// codes that the API sends. This should be used to decode errors, as all errors
// generated by the API have the same format.
func decodeErrors(res *http.Response) (interface{}, error) {
	defer res.Body.Close()

	switch res.StatusCode {
	case 400, 402, 403, 404, 405:
		ret := &types.APIError{}
		err := json.NewDecoder(res.Body).Decode(ret)
		if err != nil {
			return nil, err
		}
		return ret, nil
	case 401:
		ret := &types.TokenError{}
		err := json.NewDecoder(res.Body).Decode(ret)
		if err != nil {
			return nil, err
		}
		return ret, nil
	default:
		body, err := ioutil.ReadAll(res.Body)
		if err != nil {
			return nil, err
		}
		return string(body), nil
	}
}
